### ISSUE TITLE
[vite] The requested module '@ionited/mask-svelte' does not provide an export named 'mask'

### ISSUE THREAD

**Issue by lolcabanon** [ionited/mask-svelte#3]
Hey it's me again!

I just updated to `Vite 5.3.1` and a problem is occurring since.

`[vite] The requested module '@ionited/mask-svelte' does not provide an export named 'mask'`

Seems to be related to this commit : https://github.com/vitejs/vite/commit/f599ab4

Not sure if it's Vite's fault or yours, but I just wanted to let you know!

Tell me if you need more info on my end, or if you cannot reproduce. It should happen with `Vite 5.3.x`.

For now, I rolled back to `Vite 5.2.13` and everything works as expected.

**Comment by gabrielcursino** [comment]
Hello, @lolcabanon!

I noticed this error earlier today. I will try to fix it asap!

Thanks for reporting!

**Comment by lolcabanon** [comment]
Neat! Awesome job again :)

**Comment by lolcabanon** [comment]
I confirm it fixed my issue! Thanks :smile:
